name: Deploy React CSR
on:
  push:
    branches:
      - main
      - features/**
      - "!features/authen"
  workflow_dispatch:
  pull_request:
    types:
      - opened
env:
  BUN_VERSION: 1.2.18
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Bun version
        run: echo "API Key:${{ secrets.API_KEY }}"

      - name: Clone repo
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{vars.BUN_VERSION}}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}

      - name: Install deps
        run: bun i

      - name: Build
        run: bun run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
      - name: Force failure
        run: exit 1

  deploy:
    if: ${{ github.ref == 'gitrefs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        run: echo "Deploying..."

  notify:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    if: failure()
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build fail by สุดหล่อ'